services:
  - type: web
    name: food-good-vms-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: volunteer-management-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        value: https://food-good-vms-service.onrender.com/api/v1
